# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ffe9288d66a8ad44134a20359c346c7d09829ad3bd444a35770a36a4493b80246991d7bb3774eb34bd5cfa9e0b7cd7db2c196b4147592f5338352dba207c76

test:
  secret_key_base: 146a005e6897bb3ae945e2dd94a2742bdd83cab141a45a6f60894cd72b1f27ac16eb904419db9672019fe39d328167ea0952a05584559d92abc0c3379cabe94c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
